# Numpy assignment 

### What is python library ? why do we use python libraries
In lamon term library means is collection of book in shelf
The library are pre written code in python file which is use to import or reuses again and again
We want to save our time to write code again and again that's why we write code put it into file and reuse it and our time is also saved

### Difference between numpy array and list
1. Numpy
   It is the static contigious allocation of memeory
   It store data in static once created cannot change
   Once it created the size of numpy can't be expanded
   It is homogenous in nature
   
3. List
   It store the data dynamic allocation in memory
   The size of list can be expand
   It is hetrogenous in nature
   Use resizing and vectorization

In [1]:
import numpy as np

In [2]:
array=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [3]:
array.shape

(3, 4)

In [4]:
array.size

12

In [5]:
array.ndim

2

In [6]:
array[0]

array([1, 2, 3, 4])

In [7]:
array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [8]:
array[2][3]

np.int64(12)

In [9]:
array[array%2!=0]

array([ 1,  3,  5,  7,  9, 11])

In [30]:
matrix=np.random.randint(0,2,(3,3))

In [31]:
matrix

array([[0, 0, 1],
       [1, 0, 1],
       [1, 1, 1]], dtype=int32)

In [27]:
# matrix=np.random.randn()
matrix=np.random.random(3)

In [28]:
matrix

array([0.65456123, 0.10354694, 0.15932524])

In [32]:
matrix=np.random.rand(3,3)

In [33]:
matrix

array([[0.76052015, 0.02773461, 0.91844345],
       [0.5857454 , 0.52189458, 0.16613989],
       [0.39216737, 0.83687639, 0.37290579]])

In [36]:
np.random.randn(1,7)

array([[ 0.6121681 , -0.31488052, -0.30958582, -0.09043108, -0.34809046,
        -0.79433237,  0.27417699]])

In [37]:
np.random.rand(1,7)

array([[0.41785814, 0.86702922, 0.95132738, 0.9448713 , 0.2433278 ,
        0.50316162, 0.45088626]])

### np.random.randn(1,7) # it generate gaussian distribution 
### np.random.rand(1,7), it generate random number between 0 to 1 

In [38]:
Matrix1=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
Matrix2=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [39]:
Matrix1 + Matrix2

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24]])

In [40]:
Matrix1 - Matrix2

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [41]:
Matrix1 * Matrix2

array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144]])

In [43]:
Matrix2 / Matrix1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [48]:
# Matrix1 @ Matrix2  will rase error because it will have some shape difference

In [45]:
Matrix1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [46]:
Matrix2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [47]:
Matrix1 @ Matrix2.T

array([[ 30,  70, 110],
       [ 70, 174, 278],
       [110, 278, 446]])

In [52]:
# array.swapaxes(axis=0


In [53]:
# 12. which function of numpy can be used to swap the byter order of an ar

## In NumPy, you can use the byteswap() function to swap the byte order of an array's elements.

### 13. significan of np.linalg library
The NumPy linear algebra functions rely on BLAS and LAPACK to provide efficient
low level implementations of standard linear algebra algorithms


In [64]:
import numpy as np

arr = np.array([1, 256], dtype=np.int16)

# Swap the byte order (in-place)
arr.byteswap(inplace=True)

print(arr) 

[256   1]


### 14. np.reshape use of this
it reshape the array only when the multiplication of rows and column = size of array
example
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])
it reshape to 1 x 9 or  x 1 or 3 x 3 but it cannot reshape to  2 x 6 or 2 x 9 otherwise it raise the error

In [65]:
array=np.ones((3,3))

In [66]:
array.reshape(1,9)

array([[1., 1., 1., 1., 1., 1., 1., 1., 1.]])

### Broadcasting in numpy
Performing the arathematic operation on each and every element of array this process is called broadcasting of array
array=np.ones((3,3))
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])
to convert all value to 5 we should multiply it by 5 like this
array=array*5
array([[5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.]])


In [67]:
# convert each and every value in array
array*5

array([[5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.]])